apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
  - name: web
    image: awesomepineapple/test-web:0.3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /app
        name: app
  volumes:
    - name: app
      emptyDir: {}
  initContainers:
  - name: init-web
    image: busybox:1.35.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - mountPath: /app
        name: app

